# Default values for eventstreams instance
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
name: es-instance
apiVersion: v1beta2
#namespace: openshift-operators
version: 11.0.2
license_use: CloudPakForIntegrationNonProduction
kafka_replicas: 1
zookeeper_replicas: 1
requestIbmServices_iam: true
requestIbmServices_monitoring: true

kafka_config:
  inter_broker_protocol_version: 3.2
  log_message_format_version: 3.2

resources:
 requests:
   memory: "128Mi"
   cpu: "100m"
 limits:
   memory: "2Gi"
   cpu: "1"


authorization:
  type: runas

storage_kafka:
  type: ephemeral
  #  size: 10Gi
  # class: ""

storage_zookeeper:
  type: persistent-claim
  size: 10Gi
  class: "ibmc-vpc-block-10iops-tier"


listeners:
  - name: external
    port: 9094
    tls: true
    authentication:
      type: "scram-sha-512"
    type: route
  - name: tls
    port: 9093
    type: internal
    tls: true
    authentication:
      type: "tls"
